### ISSUE TITLE
Support for "math" in array definition?

### ISSUE THREAD

**Issue by eribe** [eventh/kpro9#10]
# define ABC 5
# define DEF 5

struct test {
    char test1[ABC + DEF - 5]; /\* Support (ABC + DEF - 5)? */
};

**Comment by eventh** [comment]
Damn, I had completely forgot about that part. Its nicely marked with a TODO in cparser :)

**Comment by eventh** [comment]
Solved by 5352830ec7f251d9d9570fcd905272fdacb629f2, closing this issue. Still no support for ID in array declaration.
