### ISSUE TITLE
Signed bitstrings

### ISSUE THREAD

**Issue by eventh** [eventh/kpro9#11]
All ints are currently forced to unsigned type in bitstring, as signed ints seems to crash Wiresharks.

**Comment by eventh** [comment]
Minimal example code which produces the bug:

``` lua
local proto_bitstring_test = Proto("bitstring_test", "Bit string test")
local f = proto_bitstring_test.fields
f.flags = ProtoField.int32("flags", "flags", base.HEX)
```

**Comment by eventh** [comment]
Not a bug, feature. Either we can force signed ints to unsigned in bitstring, or only show hex value of unsigned ints.

**Comment by stigbjorlykke** [comment]
Wireshark does not support displaying signed integers as hexadecimal, as this does not make sense.
