### ISSUE TITLE
64bit ints with valuestring (Wireshark)

### ISSUE THREAD

**Issue by eventh** [eventh/kpro9#12]
ProtoField.int64 with given a valuestring mapping as parameter will crash Wireshark. Most likely a bug in Wireshark and not CSjark.

**Comment by eventh** [comment]
Example code which crashes Wireshark:

``` lua
local test = Proto("test", "test")
test.fields.long = ProtoField.int64("l", "l", nil, {[0]="No", [1]="Yes"})
```

**Comment by eventh** [comment]
Fixed by customer in Wireshark revision 39556.

**Comment by eventh** [comment]
Reopen, as the wireshark fix had to be reverted. Still not a problem CSjark should fix itself.

**Comment by stigbjorlykke** [comment]
Wireshark does not support using value strings with 64 bit integers (yet).
