### ISSUE TITLE
Adding nodes after calling subdissectors (Wireshark)

### ISSUE THREAD

**Issue by eventh** [eventh/kpro9#16]
With struct within struct or union within union, if we try to add something to the wireshark tree inside the dissector function after we have called a subdissector on the buffer, wireshark crashes.

**Comment by Sigurdw** [comment]
Fixed this by calling the dissector directly (without going through the dissectortable). Seems like there either is a bug in how we handle the dissector table, or there is some funcy sideeffect assosiated with dissectortable from string to dissector (which is the new thing here). I will ask Stig about this.

**Comment by eventh** [comment]
We now have the same problem with calling dissectors directly in xcon.h

**Comment by stigbjorlykke** [comment]
I found a bug in Wireshark in the functions registering new Lua dissectors, where the dissector name would be garbage collected when loading a capture file.  This bug is corrected in revision 39681.

**Comment by eventh** [comment]
Seems to work with Wireshark revision 39684, closing this issue.
