### ISSUE TITLE
Improve typedef

### ISSUE THREAD

**Issue by eribe** [eventh/kpro9#6]
Support for the typedef keyword need to be improved. typedef enum is not supported, probably more.

**Comment by eventh** [comment]
Solved by aaea74f7116af32a829ea4cd37d5b02940b1af3a I think, might need some testing.

**Comment by eventh** [comment]
Still missing support for typedef arrays, reopened.

**Comment by eventh** [comment]
Finally fixed by 92161fc49f05fc16a36076460f9d0f943bd1ad7b, closing.
